POST http://localhost:3000/register/
Content-Type:application/json

{
  "username": "adam_richard",
  "password": "richard_567",
  "name": "Adam Richard",
  "gender": "male"
}
### 

POST http://localhost:3000/login/ 
Content-Type: application/json

{
   "username":"JoeBiden",
  "password":"biden@123"
}
###
GET http://localhost:3000/user/tweets/feed/
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNzAwNTUwMDE3fQ._s6DawkLoo5ee0LAPS3G7UtajXJ788AGsPL14FZp8os
###

 
GET http://localhost:3000/user/following/
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNzAwNTUwMDE3fQ._s6DawkLoo5ee0LAPS3G7UtajXJ788AGsPL14FZp8os

###

GET http://localhost:3000/user/followers/
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNzAwNTUwMDE3fQ._s6DawkLoo5ee0LAPS3G7UtajXJ788AGsPL14FZp8os
###

GET http://localhost:3000/tweets/7/
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNzAwNTUwMDE3fQ._s6DawkLoo5ee0LAPS3G7UtajXJ788AGsPL14FZp8os
###

GET http://localhost:3000/tweets/1/likes/
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNzAwNTUwMDE3fQ._s6DawkLoo5ee0LAPS3G7UtajXJ788AGsPL14FZp8os
###

GET http://localhost:3000/tweets/2/replies/
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNzAwNTUwMDE3fQ._s6DawkLoo5ee0LAPS3G7UtajXJ788AGsPL14FZp8os
###

GET http://localhost:3000/user/tweets/
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNzAwNTUwMDE3fQ._s6DawkLoo5ee0LAPS3G7UtajXJ788AGsPL14FZp8os
###
POST http://localhost:3000/user/tweets/
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNzAwNTUwMDE3fQ._s6DawkLoo5ee0LAPS3G7UtajXJ788AGsPL14FZp8os

{
   "tweet": "The Mornings..."
}

###

DELETE http://localhost:3000/tweets/3/
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNzAwNTUwMDE3fQ._s6DawkLoo5ee0LAPS3G7UtajXJ788AGsPL14FZp8os


